name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'   # matches v1.0.0, v2.3.4 etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # adjust for your target

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}

      - name: Pack
        run: dotnet pack --configuration Release /p:PackageVersion=${{ env.VERSION }} -o ./artifacts

      - name: Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
